"""baseline schema

Revision ID: 0002_baseline_schema
Revises: 0001_enable_pgvector
Create Date: 2026-06-04 22:09:04.076083
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '0002_baseline_schema'
down_revision: str | None = '0001_enable_pgvector'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('approved_answer_library',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('question_external_id', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_detail', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'source', 'question_external_id', name='uq_approved_answer_src_qid')
    )
    op.create_index(op.f('ix_approved_answer_library_org_id'), 'approved_answer_library', ['org_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_table('company_profile',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('raw_markdown', sa.Text(), nullable=False),
    sa.Column('key_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profile_org_id'), 'company_profile', ['org_id'], unique=False)
    op.create_table('controls',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('control_code', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('implementation_statement', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('framework_mappings', sa.Text(), nullable=True),
    sa.Column('last_reviewed', sa.Date(), nullable=True),
    sa.Column('next_review', sa.Date(), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'control_code', name='uq_control_org_code')
    )
    op.create_index(op.f('ix_controls_org_id'), 'controls', ['org_id'], unique=False)
    op.create_table('evidence',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('confidentiality', sa.String(length=32), nullable=False),
    sa.Column('customer_shareable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_org_id'), 'evidence', ['org_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_org_id'), 'knowledge_chunks', ['org_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_source_id'), 'knowledge_chunks', ['source_id'], unique=False)
    op.create_table('questionnaires',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('source_format', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaires_org_id'), 'questionnaires', ['org_id'], unique=False)
    op.create_table('evidence_control_links',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'control_id', name='uq_evidence_control')
    )
    op.create_index(op.f('ix_evidence_control_links_org_id'), 'evidence_control_links', ['org_id'], unique=False)
    op.create_table('questions',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('questionnaire_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_org_id'), 'questions', ['org_id'], unique=False)
    op.create_index(op.f('ix_questions_questionnaire_id'), 'questions', ['questionnaire_id'], unique=False)
    op.create_table('answers',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('short_answer', sa.String(length=512), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('claim', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exceptions', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('freshness_status', sa.String(length=32), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_org_id'), 'answers', ['org_id'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_table('answer_reviews',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_reviews_answer_id'), 'answer_reviews', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_reviews_org_id'), 'answer_reviews', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_reviews_org_id'), table_name='answer_reviews')
    op.drop_index(op.f('ix_answer_reviews_answer_id'), table_name='answer_reviews')
    op.drop_table('answer_reviews')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_org_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_questionnaire_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_org_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_evidence_control_links_org_id'), table_name='evidence_control_links')
    op.drop_table('evidence_control_links')
    op.drop_index(op.f('ix_questionnaires_org_id'), table_name='questionnaires')
    op.drop_table('questionnaires')
    op.drop_index(op.f('ix_knowledge_chunks_source_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_org_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_evidence_org_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_controls_org_id'), table_name='controls')
    op.drop_table('controls')
    op.drop_index(op.f('ix_company_profile_org_id'), table_name='company_profile')
    op.drop_table('company_profile')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_approved_answer_library_org_id'), table_name='approved_answer_library')
    op.drop_table('approved_answer_library')
    op.drop_table('organization')
    # ### end Alembic commands ###
